- name: nagios installation (Ubuntu)
  apt: 
    name:
      - nagios4
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: nagios installation (CentOS)
  dnf:
     name:
       - nagios
     state: latest
     update_cache: yes
  when: ansible_distribution == "CentOS"

